#!/usr/bin/env node
/**
 * iTaK npm postinstall script
 * 
 * Runs after `npm install itak` to:
 * 1. Install Python package via pip
 * 2. Check/setup Docker services (ChromaDB, Playwright, SearXNG)
 * 3. Pull default LLM model via Ollama
 * 4. Launch the iTaK CLI with welcome screen
 */

const { execSync, spawn, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

const DEFAULT_MODEL = 'qwen3-vl:2b';

// Required Docker services with their default ports
const DOCKER_SERVICES = [
    { name: 'chromadb', container: 'shared-chromadb', image: 'chromadb/chroma', port: 8000, envVar: 'CHROMADB_URL', required: true },
    { name: 'ollama', container: 'ollama', image: 'ollama/ollama', port: 11434, envVar: 'OLLAMA_URL', required: true },
    { name: 'playwright', container: 'playwright', image: 'mcr.microsoft.com/playwright', port: 3000, envVar: 'PLAYWRIGHT_URL', required: false },
    { name: 'searxng', container: 'searxng', image: 'searxng/searxng', port: 8080, envVar: 'SEARXNG_URL', required: false },
];

console.log('\n' + '='.repeat(60));
console.log('  iTaK Agent Framework - Installing...');
console.log('='.repeat(60) + '\n');

// Detect Python command
function getPythonCommand() {
    const commands = ['python3', 'python', 'py'];
    for (const cmd of commands) {
        try {
            execSync(`${cmd} --version`, { stdio: 'ignore' });
            return cmd;
        } catch (e) {
            continue;
        }
    }
    return null;
}

// Check if Docker is available
function checkDocker() {
    try {
        execSync('docker --version', { stdio: 'ignore' });
        return true;
    } catch (e) {
        return false;
    }
}

// Get running Docker containers
function getRunningContainers() {
    try {
        const result = execSync('docker ps --format "{{.Names}}"', { encoding: 'utf8' });
        return result.split('\n').filter(n => n.trim());
    } catch (e) {
        return [];
    }
}

// Check if Ollama is available (Docker or native)
function checkOllama() {
    try {
        execSync('ollama list', { stdio: 'ignore', timeout: 5000 });
        return true;
    } catch (e) {
        return false;
    }
}

// Check if model is installed in Ollama
function checkModelInstalled(model) {
    try {
        const result = execSync('ollama list', { encoding: 'utf8', timeout: 10000 });
        const modelBase = model.split(':')[0];
        return result.includes(modelBase);
    } catch (e) {
        return false;
    }
}

// Pull model via Ollama
function pullModel(model) {
    console.log(`  📦 Pulling model: ${model}...`);
    console.log('     (This may take a few minutes on first run)\n');

    try {
        spawnSync('ollama', ['pull', model], {
            stdio: 'inherit',
            shell: true,
            timeout: 600000 // 10 minute timeout
        });
        return true;
    } catch (e) {
        console.log(`  ⚠️  Failed to pull model: ${e.message}`);
        return false;
    }
}

// Check Docker services
function checkDockerServices() {
    console.log('  🐳 Checking Docker services...\n');

    if (!checkDocker()) {
        console.log('  ⚠️  Docker not found. Some features may be limited.');
        console.log('     Install Docker: https://docs.docker.com/get-docker/\n');
        return;
    }

    const running = getRunningContainers();

    for (const service of DOCKER_SERVICES) {
        // Check both the expected container name and common variations
        const isRunning = running.some(name =>
            name.includes(service.name) ||
            name === service.container
        );

        if (isRunning) {
            console.log(`  ✅ ${service.name}: Running`);
        } else if (service.required) {
            console.log(`  ⚠️  ${service.name}: Not running (required)`);
            console.log(`      → docker run -d --name ${service.container} ${service.image}`);
        } else {
            console.log(`  ⏭️  ${service.name}: Not running (optional)`);
        }
    }
    console.log();
}

// Generate .env file with Docker service URLs
function generateEnvFile() {
    console.log('  📝 Generating .env file...\n');

    const projectRoot = __dirname.replace('/scripts', '').replace('\\scripts', '');
    const envPath = path.join(projectRoot, '.env');

    // Check if .env already exists
    let existingEnv = {};
    if (fs.existsSync(envPath)) {
        const content = fs.readFileSync(envPath, 'utf8');
        content.split('\n').forEach(line => {
            const [key, ...valueParts] = line.split('=');
            if (key && valueParts.length > 0) {
                existingEnv[key.trim()] = valueParts.join('=').trim();
            }
        });
    }

    const running = getRunningContainers();

    // Build env vars for running services
    const envVars = {
        '# iTaK Agent Framework Environment Configuration': '',
        '# Auto-generated by npm install': '',
        '': '',
        '# Default LLM Model': '',
        'ITAK_DEFAULT_MODEL': DEFAULT_MODEL,
        '': '',
        '# Docker Service URLs': '',
    };

    for (const service of DOCKER_SERVICES) {
        const isRunning = running.some(name =>
            name.includes(service.name) ||
            name === service.container
        );

        if (isRunning) {
            // Use localhost for local Docker containers
            envVars[service.envVar] = `http://localhost:${service.port}`;
            console.log(`  ✅ ${service.envVar}=http://localhost:${service.port}`);
        } else {
            // Comment out if not running
            envVars[`# ${service.envVar}`] = `http://localhost:${service.port}  # Not running`;
            console.log(`  ⏭️  ${service.envVar} (service not running)`);
        }
    }

    // Add any existing custom vars that aren't being overwritten
    envVars[''] = '';
    envVars['# Custom Configuration'] = '';
    for (const [key, value] of Object.entries(existingEnv)) {
        if (!key.startsWith('#') && !DOCKER_SERVICES.some(s => s.envVar === key) && key !== 'ITAK_DEFAULT_MODEL') {
            envVars[key] = value;
        }
    }

    // Write .env file
    const envContent = Object.entries(envVars)
        .map(([key, value]) => {
            if (key === '' || key.startsWith('#')) {
                return key;
            }
            return `${key}=${value}`;
        })
        .join('\n');

    fs.writeFileSync(envPath, envContent + '\n');
    console.log(`\n  ✅ .env file created at: ${envPath}\n`);
}

// Check and pull default LLM
function setupDefaultModel() {
    console.log('  🤖 Checking default LLM model...\n');

    if (!checkOllama()) {
        console.log('  ⚠️  Ollama not available. Cannot verify model.');
        console.log('     Install Ollama: https://ollama.ai\n');
        return;
    }

    if (checkModelInstalled(DEFAULT_MODEL)) {
        console.log(`  ✅ Model ${DEFAULT_MODEL}: Installed\n`);
        return;
    }

    console.log(`  📥 Model ${DEFAULT_MODEL}: Not found`);
    pullModel(DEFAULT_MODEL);
}

// Install Python package
function installPythonPackage() {
    const python = getPythonCommand();

    if (!python) {
        console.log('  ⚠️  Python not found!');
        console.log('  Please install Python 3.10+ first:');
        console.log('  → https://www.python.org/downloads/\n');
        return false;
    }

    console.log(`  ✅ Found Python: ${python}`);
    console.log('  📦 Installing iTaK Python package...\n');

    try {
        // Try local install first (editable mode for development)
        execSync(`${python} -m pip install -e . --quiet`, {
            stdio: 'inherit',
            cwd: __dirname.replace('/scripts', '').replace('\\scripts', ''),
            timeout: 300000 // 5 minute timeout
        });
        console.log('\n  ✅ Python package installed!');
        return true;
    } catch (e) {
        console.log('  ⚠️  Local install failed, trying PyPI...');
        try {
            execSync(`${python} -m pip install itak --quiet`, {
                stdio: 'inherit',
                timeout: 300000
            });
            console.log('\n  ✅ Python package installed (from PyPI)!');
            return true;
        } catch (e2) {
            console.log('\n  ❌ Failed to install Python package');
            return false;
        }
    }
}

// Launch iTaK CLI
function launchCLI() {
    console.log('\n  🚀 Launching iTaK...\n');

    try {
        spawnSync('itak', [], {
            stdio: 'inherit',
            shell: true
        });
    } catch (e) {
        console.log('\n  ✅ Installation complete!');
        console.log('  Run `itak` to start the iTaK Agent Framework\n');
    }
}

// Main
async function main() {
    // Step 1: Check Docker services
    checkDockerServices();

    // Step 2: Generate .env file with service URLs
    generateEnvFile();

    // Step 3: Install Python package
    const success = installPythonPackage();

    // Step 4: Setup default model
    if (success) {
        setupDefaultModel();
    }

    // Step 5: Launch CLI
    if (success) {
        launchCLI();
    } else {
        console.log('\n  Manual install:');
        console.log('  pip install itak');
        console.log('  itak\n');
    }
}

main();
